CREATE TABLE [dbo].[Members]
(
	[MemberSeq] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [MemberID] VARCHAR(255) NOT NULL, 
    [Password] NVARCHAR(512) NOT NULL,
    [MemberType] NVARCHAR(50) NOT NULL, 
    [SubMemberType] NVARCHAR(50) NULL, 
    [IDType] NVARCHAR(50) NOT NULL, 
    [Email] VARCHAR(255) NULL, 
    [RegistDate] DATETIME2 NOT NULL DEFAULT getdate(), 
    [LastUpdate] DATETIME2 NOT NULL DEFAULT getdate(), 
    [LastLogin] DATETIME2 NOT NULL DEFAULT getdate(), 
    [MemberStatus] NVARCHAR(50) NOT NULL, 
    [IsCrypto] bit NOT NULL DEFAULT 0 ,
    [ExtraColumn01] NVARCHAR(250) NULL, 
    [ExtraColumn02] NVARCHAR(250) NULL, 
    [ExtraColumn03] NVARCHAR(250) NULL, 
    [ExtraColumn04] NVARCHAR(250) NULL, 
    [ExtraColumn05] NVARCHAR(250) NULL, 
    [ExtraColumn06] NVARCHAR(250) NULL, 
    [ExtraColumn07] NVARCHAR(250) NULL, 
    [ExtraColumn08] NVARCHAR(250) NULL, 
    [ExtraColumn09] NVARCHAR(250) NULL, 
    [ExtraColumn10] NVARCHAR(250) NULL, 
    [ExtraColumn11] NVARCHAR(250) NULL, 
    [ExtraColumn12] NVARCHAR(250) NULL, 
    [ExtraColumn13] NVARCHAR(250) NULL, 
    [ExtraColumn14] NVARCHAR(250) NULL, 
    [ExtraColumn15] NVARCHAR(250) NULL, 
    [ExtraColumn16] NVARCHAR(250) NULL, 
    [ExtraColumn17] NVARCHAR(250) NULL, 
    [ExtraColumn18] NVARCHAR(250) NULL, 
    [ExtraColumn19] NVARCHAR(250) NULL, 
    [ExtraColumn20] NVARCHAR(250) NULL, 
    [ExtraColumn21] NVARCHAR(250) NULL, 
    [ExtraColumn22] NVARCHAR(250) NULL, 
    [ExtraColumn23] NVARCHAR(250) NULL, 
    [ExtraColumn24] NVARCHAR(250) NULL, 
    [ExtraColumn25] NVARCHAR(250) NULL, 
    [ExtraColumn26] NVARCHAR(250) NULL, 
    [ExtraColumn27] NVARCHAR(250) NULL, 
    [ExtraColumn28] NVARCHAR(250) NULL, 
    [ExtraColumn29] NVARCHAR(250) NULL, 
    [ExtraColumn30] NVARCHAR(250) NULL, 
    [IsEnabled] bit DEFAULT 1 NOT NULL
)

GO

CREATE UNIQUE INDEX [IX_Members_ID] ON [dbo].[Members] ([MemberID] DESC)
