CREATE TABLE [dbo].[Boards]
(
	[BoardSeq] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [BmSeq] BIGINT NOT NULL,
    [Title] NVARCHAR(100) NOT NULL, 
    [Content] NVARCHAR(MAX) NOT NULL, 
    [Answer] NVARCHAR(MAX) NULL, 
    [AnswerDate] datetime2 NOT NULL DEFAULT getdate(),
    [BoardStatus] nvarchar(50) NULL,
    [ReadCount] INT NOT NULL DEFAULT 0, 
    [Depth] INT NOT NULL DEFAULT 0, 
    [ParentBoardSeq] BIGINT NOT NULL DEFAULT -1, 
    [RegistDate] DATETIME2 NOT NULL DEFAULT getdate(), 
    [LastUpdate] DATETIME2 NOT NULL DEFAULT getdate(), 
    [RecommendCount] INT NOT NULL DEFAULT 0, 
    [LikeCount] INT NOT NULL DEFAULT 0, 
    [UnLikeCount] INT NOT NULL DEFAULT 0, 
    [ShareCount] INT NOT NULL DEFAULT 0, 
    [MemberSeq] BIGINT NULL, 
    [Password] VARCHAR(30) NULL, 
    [ExtraColumn01] NVARCHAR(250) NULL, 
    [ExtraColumn02] NVARCHAR(250) NULL, 
    [ExtraColumn03] NVARCHAR(250) NULL, 
    [ExtraColumn04] NVARCHAR(250) NULL, 
    [ExtraColumn05] NVARCHAR(250) NULL, 
    [ExtraColumn06] NVARCHAR(250) NULL, 
    [ExtraColumn07] NVARCHAR(250) NULL, 
    [ExtraColumn08] NVARCHAR(250) NULL, 
    [ExtraColumn09] NVARCHAR(250) NULL, 
    [ExtraColumn10] NVARCHAR(250) NULL, 
    [ExtraColumn11] NVARCHAR(250) NULL, 
    [ExtraColumn12] NVARCHAR(250) NULL, 
    [ExtraColumn13] NVARCHAR(250) NULL, 
    [ExtraColumn14] NVARCHAR(250) NULL, 
    [ExtraColumn15] NVARCHAR(250) NULL, 
    [ExtraColumn16] NVARCHAR(250) NULL, 
    [ExtraColumn17] NVARCHAR(250) NULL, 
    [ExtraColumn18] NVARCHAR(250) NULL, 
    [ExtraColumn19] NVARCHAR(250) NULL, 
    [ExtraColumn20] NVARCHAR(250) NULL, 
    [ExtraColumn21] NVARCHAR(250) NULL, 
    [ExtraColumn22] NVARCHAR(250) NULL, 
    [ExtraColumn23] NVARCHAR(250) NULL, 
    [ExtraColumn24] NVARCHAR(250) NULL, 
    [ExtraColumn25] NVARCHAR(250) NULL, 
    [ExtraColumn26] NVARCHAR(250) NULL, 
    [ExtraColumn27] NVARCHAR(250) NULL, 
    [ExtraColumn28] NVARCHAR(250) NULL, 
    [ExtraColumn29] NVARCHAR(250) NULL, 
    [ExtraColumn30] NVARCHAR(250) NULL, 
    [IsEnabled] bit DEFAULT 1 NOT NULL, 
    [IsShow] BIT NOT NULL DEFAULT 1
)
