using System.Collections.Generic;

namespace WEC_Builder
{
    public class CreateTableQuery
    {
        public List<string> All { get; set; } = new List<string>();

        public CreateTableQuery()
        {
            this.All.Add(Categories);
            this.All.Add(Members);
            this.All.Add(ExtraMasters);
            this.All.Add(MemberTokens);
            this.All.Add(BoardMasters);
            this.All.Add(Boards);
            this.All.Add(BoardActionLog);
            this.All.Add(DynamicPageMaster);
            this.All.Add(DynamicPageDetail);
        }

        public string Categories =
@"CREATE TABLE [dbo].[Categories] (
    [CategorySeq] BIGINT         IDENTITY (1, 1) NOT NULL,
    [Key1]        NVARCHAR (50)  NULL,
    [Key2]        NVARCHAR (50)  NULL,
    [Key3]        NVARCHAR (50)  NULL,
    [Key4]        NVARCHAR (50)  NULL,
    [Key5]        NVARCHAR (50)  NULL,
    [Key6]        NVARCHAR (50)  NULL,
    [Key7]        NVARCHAR (50)  NULL,
    [Key8]        NVARCHAR (50)  NULL,
    [Key9]        NVARCHAR (50)  NULL,
    [Value1]      NVARCHAR (250) NULL,
    [Value2]      NVARCHAR (250) NULL,
    [Value3]      NVARCHAR (250) NULL,
    [Value4]      NVARCHAR (250) NULL,
    [Value5]      NVARCHAR (250) NULL,
    [Value6]      NVARCHAR (250) NULL,
    [Value7]      NVARCHAR (250) NULL,
    [Value8]      NVARCHAR (250) NULL,
    [Value9]      NVARCHAR (250) NULL,
    [IsEnabled]   BIT            NOT NULL,
    PRIMARY KEY CLUSTERED ([CategorySeq] ASC)
);";

        public string Members =
@"
CREATE TABLE [dbo].[Members] (
    [MemberSeq]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [MemberID]      VARCHAR (255)  NOT NULL,
    [Password]      NVARCHAR (512) NOT NULL,
	[ViewName]      NVARCHAR (50)  NOT NULL,
    [MemberType]    NVARCHAR (50)  NOT NULL,
    [SubMemberType] NVARCHAR (50)  NULL,
    [IDType]        NVARCHAR (50)  NOT NULL,
    [Email]         VARCHAR (255)  NULL,
    [RegistDate]    DATETIME2 (7)  NOT NULL,
    [LastUpdate]    DATETIME2 (7)  NOT NULL,
    [LastLogin]     DATETIME2 (7)  NOT NULL,
    [MemberStatus]  NVARCHAR (50)  NOT NULL,
    [IsCrypto]      BIT            NOT NULL,
    [ExtraColumn01] NVARCHAR (250) NULL,
    [ExtraColumn02] NVARCHAR (250) NULL,
    [ExtraColumn03] NVARCHAR (250) NULL,
    [ExtraColumn04] NVARCHAR (250) NULL,
    [ExtraColumn05] NVARCHAR (250) NULL,
    [ExtraColumn06] NVARCHAR (250) NULL,
    [ExtraColumn07] NVARCHAR (250) NULL,
    [ExtraColumn08] NVARCHAR (250) NULL,
    [ExtraColumn09] NVARCHAR (250) NULL,
    [ExtraColumn10] NVARCHAR (250) NULL,
    [ExtraColumn11] NVARCHAR (250) NULL,
    [ExtraColumn12] NVARCHAR (250) NULL,
    [ExtraColumn13] NVARCHAR (250) NULL,
    [ExtraColumn14] NVARCHAR (250) NULL,
    [ExtraColumn15] NVARCHAR (250) NULL,
    [ExtraColumn16] NVARCHAR (250) NULL,
    [ExtraColumn17] NVARCHAR (250) NULL,
    [ExtraColumn18] NVARCHAR (250) NULL,
    [ExtraColumn19] NVARCHAR (250) NULL,
    [ExtraColumn20] NVARCHAR (250) NULL,
    [ExtraColumn21] NVARCHAR (250) NULL,
    [ExtraColumn22] NVARCHAR (250) NULL,
    [ExtraColumn23] NVARCHAR (250) NULL,
    [ExtraColumn24] NVARCHAR (250) NULL,
    [ExtraColumn25] NVARCHAR (250) NULL,
    [ExtraColumn26] NVARCHAR (250) NULL,
    [ExtraColumn27] NVARCHAR (250) NULL,
    [ExtraColumn28] NVARCHAR (250) NULL,
    [ExtraColumn29] NVARCHAR (250) NULL,
    [ExtraColumn30] NVARCHAR (250) NULL,
    [IsEnabled]     BIT            NOT NULL,
    PRIMARY KEY CLUSTERED ([MemberSeq] ASC)
);";

        public string ExtraMasters =
@"CREATE TABLE [dbo].[ExtraMasters] (
    [EmSeq]         BIGINT        IDENTITY (1, 1) NOT NULL,
    [TableName]     VARCHAR (255) NOT NULL,
    [ExtraColumn01] NVARCHAR (50) NULL,
    [ExtraColumn02] NVARCHAR (50) NULL,
    [ExtraColumn03] NVARCHAR (50) NULL,
    [ExtraColumn04] NVARCHAR (50) NULL,
    [ExtraColumn05] NVARCHAR (50) NULL,
    [ExtraColumn06] NVARCHAR (50) NULL,
    [ExtraColumn07] NVARCHAR (50) NULL,
    [ExtraColumn08] NVARCHAR (50) NULL,
    [ExtraColumn09] NVARCHAR (50) NULL,
    [ExtraColumn10] NVARCHAR (50) NULL,
    [ExtraColumn11] NVARCHAR (50) NULL,
    [ExtraColumn12] NVARCHAR (50) NULL,
    [ExtraColumn13] NVARCHAR (50) NULL,
    [ExtraColumn14] NVARCHAR (50) NULL,
    [ExtraColumn15] NVARCHAR (50) NULL,
    [ExtraColumn16] NVARCHAR (50) NULL,
    [ExtraColumn17] NVARCHAR (50) NULL,
    [ExtraColumn18] NVARCHAR (50) NULL,
    [ExtraColumn19] NVARCHAR (50) NULL,
    [ExtraColumn20] NVARCHAR (50) NULL,
    [ExtraColumn21] NVARCHAR (50) NULL,
    [ExtraColumn22] NVARCHAR (50) NULL,
    [ExtraColumn23] NVARCHAR (50) NULL,
    [ExtraColumn24] NVARCHAR (50) NULL,
    [ExtraColumn25] NVARCHAR (50) NULL,
    [ExtraColumn26] NVARCHAR (50) NULL,
    [ExtraColumn27] NVARCHAR (50) NULL,
    [ExtraColumn28] NVARCHAR (50) NULL,
    [ExtraColumn29] NVARCHAR (50) NULL,
    [ExtraColumn30] NVARCHAR (50) NULL,
    [IsEnabled]     BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([EmSeq] ASC)
);";

        public string MemberTokens =
@"CREATE TABLE [dbo].[MemberTokens] (
    [MtSeq]       BIGINT        IDENTITY (1, 1) NOT NULL,
    [MemberSeq]   BIGINT        NOT NULL,
    [Token]       VARCHAR (100) NOT NULL,
    [RegistDate]  DATETIME2 (7) NOT NULL,
    [ExpiredDate] DATETIME2 (7) NOT NULL,
    [IsEnabled]   BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([MtSeq] ASC)
);";

        public string BoardMasters =
@"CREATE TABLE [dbo].[BoardMasters] (
    [BmSeq]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [Title]           NVARCHAR (50)   NOT NULL,
    [SubTitle]        NVARCHAR (100)  NULL,
    [Description]     NVARCHAR (1000) NULL,
    [BmCode]          VARCHAR (50)    NULL,
    [IsPrivate]       BIT             NOT NULL,
    [IsSecret]        BIT             NOT NULL,
    [IsOnlyAdmin]     BIT             NOT NULL,
    [IsComment]       BIT             NOT NULL,
    [IsReply]         BIT             NOT NULL,
    [IsShow]          BIT             NOT NULL,
    [IsFileUpload]    BIT             NOT NULL,
    [IsAnswer]        BIT             NOT NULL,
    [IsRequiredLogin] BIT             NOT NULL,
    [IsEnabled]       BIT             NOT NULL,
    PRIMARY KEY CLUSTERED ([BmSeq] ASC)
);";

        public string Boards =
@"CREATE TABLE [dbo].[Boards] (
    [BoardSeq]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [BmSeq]          BIGINT         NOT NULL,
    [Title]          NVARCHAR (100) NOT NULL,
    [Content]        NVARCHAR (MAX) NOT NULL,
    [Answer]         NVARCHAR (MAX) NULL,
    [AnswerDate]     DATETIME2 (7)  NOT NULL,
    [BoardStatus]    NVARCHAR (50)  NULL,
    [ReadCount]      INT            NOT NULL,
    [Depth]          INT            NOT NULL,
    [ParentBoardSeq] BIGINT         NOT NULL,
    [RegistDate]     DATETIME2 (7)  NOT NULL,
    [LastUpdate]     DATETIME2 (7)  NOT NULL,
    [RecommendCount] INT            NOT NULL,
    [LikeCount]      INT            NOT NULL,
    [UnLikeCount]    INT            NOT NULL,
    [ShareCount]     INT            NOT NULL,
    [MemberSeq]      BIGINT         NULL,
    [Password]       VARCHAR (30)   NULL,
    [ExtraColumn01]  NVARCHAR (250) NULL,
    [ExtraColumn02]  NVARCHAR (250) NULL,
    [ExtraColumn03]  NVARCHAR (250) NULL,
    [ExtraColumn04]  NVARCHAR (250) NULL,
    [ExtraColumn05]  NVARCHAR (250) NULL,
    [ExtraColumn06]  NVARCHAR (250) NULL,
    [ExtraColumn07]  NVARCHAR (250) NULL,
    [ExtraColumn08]  NVARCHAR (250) NULL,
    [ExtraColumn09]  NVARCHAR (250) NULL,
    [ExtraColumn10]  NVARCHAR (250) NULL,
    [ExtraColumn11]  NVARCHAR (250) NULL,
    [ExtraColumn12]  NVARCHAR (250) NULL,
    [ExtraColumn13]  NVARCHAR (250) NULL,
    [ExtraColumn14]  NVARCHAR (250) NULL,
    [ExtraColumn15]  NVARCHAR (250) NULL,
    [ExtraColumn16]  NVARCHAR (250) NULL,
    [ExtraColumn17]  NVARCHAR (250) NULL,
    [ExtraColumn18]  NVARCHAR (250) NULL,
    [ExtraColumn19]  NVARCHAR (250) NULL,
    [ExtraColumn20]  NVARCHAR (250) NULL,
    [ExtraColumn21]  NVARCHAR (250) NULL,
    [ExtraColumn22]  NVARCHAR (250) NULL,
    [ExtraColumn23]  NVARCHAR (250) NULL,
    [ExtraColumn24]  NVARCHAR (250) NULL,
    [ExtraColumn25]  NVARCHAR (250) NULL,
    [ExtraColumn26]  NVARCHAR (250) NULL,
    [ExtraColumn27]  NVARCHAR (250) NULL,
    [ExtraColumn28]  NVARCHAR (250) NULL,
    [ExtraColumn29]  NVARCHAR (250) NULL,
    [ExtraColumn30]  NVARCHAR (250) NULL,
    [IsEnabled]      BIT            NOT NULL,
	[IsShow] BIT NOT NULL DEFAULT 1,
    PRIMARY KEY CLUSTERED ([BoardSeq] ASC)
);";

        public string BoardActionLog =
@"CREATE TABLE [dbo].[BoardActionLog] (
    [BoardSeq]   BIGINT        NOT NULL,
    [MemberSeq]  BIGINT        NOT NULL,
    [Column]     VARCHAR (50)  NOT NULL,
    [RegistDate] DATETIME2 (7) NOT NULL
);";

        public string DynamicPageMaster =
@"CREATE TABLE [dbo].[DynamicPageMaster] (
    [DpmSeq]       INT            IDENTITY (1, 1) NOT NULL,
    [DpmCode]      NVARCHAR (50)  NULL,
    [Title]        NVARCHAR (50)  NOT NULL,
    [RegistDate]   DATETIME2 (7)  NOT NULL,
    [RegistMember] BIGINT         NOT NULL,
    [LastUpdate]   DATETIME2 (7)  NOT NULL,
    [UpdateMember] BIGINT         NOT NULL,
    [IsEnabled]    BIT            NOT NULL,
    [ExType00]     VARCHAR (30)   NULL,
    [ExType01]     VARCHAR (30)   NULL,
    [ExType02]     VARCHAR (30)   NULL,
    [ExType03]     VARCHAR (30)   NULL,
    [ExType04]     VARCHAR (30)   NULL,
    [ExType05]     VARCHAR (30)   NULL,
    [ExType06]     VARCHAR (30)   NULL,
    [ExType07]     VARCHAR (30)   NULL,
    [ExType08]     VARCHAR (30)   NULL,
    [ExType09]     VARCHAR (30)   NULL,
    [ExType10]     VARCHAR (30)   NULL,
    [ExType11]     VARCHAR (30)   NULL,
    [ExType12]     VARCHAR (30)   NULL,
    [ExType13]     VARCHAR (30)   NULL,
    [ExType14]     VARCHAR (30)   NULL,
    [ExType15]     VARCHAR (30)   NULL,
    [ExType16]     VARCHAR (30)   NULL,
    [ExType17]     VARCHAR (30)   NULL,
    [ExType18]     VARCHAR (30)   NULL,
    [ExType19]     VARCHAR (30)   NULL,
    [ExType20]     VARCHAR (30)   NULL,
    [ExType21]     VARCHAR (30)   NULL,
    [ExType22]     VARCHAR (30)   NULL,
    [ExType23]     VARCHAR (30)   NULL,
    [ExType24]     VARCHAR (30)   NULL,
    [ExType25]     VARCHAR (30)   NULL,
    [ExType26]     VARCHAR (30)   NULL,
    [ExType27]     VARCHAR (30)   NULL,
    [ExType28]     VARCHAR (30)   NULL,
    [ExType29]     VARCHAR (30)   NULL,
    [ExType30]     VARCHAR (30)   NULL,
    [ExType31]     VARCHAR (30)   NULL,
    [ExType32]     VARCHAR (30)   NULL,
    [ExType33]     VARCHAR (30)   NULL,
    [ExType34]     VARCHAR (30)   NULL,
    [ExType35]     VARCHAR (30)   NULL,
    [ExType36]     VARCHAR (30)   NULL,
    [ExType37]     VARCHAR (30)   NULL,
    [ExType38]     VARCHAR (30)   NULL,
    [ExType39]     VARCHAR (30)   NULL,
    [ExType40]     VARCHAR (30)   NULL,
    [ExType41]     VARCHAR (30)   NULL,
    [ExType42]     VARCHAR (30)   NULL,
    [ExType43]     VARCHAR (30)   NULL,
    [ExType44]     VARCHAR (30)   NULL,
    [ExType45]     VARCHAR (30)   NULL,
    [ExType46]     VARCHAR (30)   NULL,
    [ExType47]     VARCHAR (30)   NULL,
    [ExType48]     VARCHAR (30)   NULL,
    [ExType49]     VARCHAR (30)   NULL,
    [Extra00]      NVARCHAR (30)  NULL,
    [Extra01]      NVARCHAR (30)  NULL,
    [Extra02]      NVARCHAR (30)  NULL,
    [Extra03]      NVARCHAR (30)  NULL,
    [Extra04]      NVARCHAR (30)  NULL,
    [Extra05]      NVARCHAR (30)  NULL,
    [Extra06]      NVARCHAR (30)  NULL,
    [Extra07]      NVARCHAR (30)  NULL,
    [Extra08]      NVARCHAR (30)  NULL,
    [Extra09]      NVARCHAR (30)  NULL,
    [Extra10]      NVARCHAR (30)  NULL,
    [Extra11]      NVARCHAR (30)  NULL,
    [Extra12]      NVARCHAR (30)  NULL,
    [Extra13]      NVARCHAR (30)  NULL,
    [Extra14]      NVARCHAR (30)  NULL,
    [Extra15]      NVARCHAR (30)  NULL,
    [Extra16]      NVARCHAR (30)  NULL,
    [Extra17]      NVARCHAR (30)  NULL,
    [Extra18]      NVARCHAR (30)  NULL,
    [Extra19]      NVARCHAR (30)  NULL,
    [Extra20]      NVARCHAR (30)  NULL,
    [Extra21]      NVARCHAR (30)  NULL,
    [Extra22]      NVARCHAR (30)  NULL,
    [Extra23]      NVARCHAR (30)  NULL,
    [Extra24]      NVARCHAR (30)  NULL,
    [Extra25]      NVARCHAR (30)  NULL,
    [Extra26]      NVARCHAR (30)  NULL,
    [Extra27]      NVARCHAR (30)  NULL,
    [Extra28]      NVARCHAR (30)  NULL,
    [Extra29]      NVARCHAR (30)  NULL,
    [Extra30]      NVARCHAR (30)  NULL,
    [Extra31]      NVARCHAR (30)  NULL,
    [Extra32]      NVARCHAR (30)  NULL,
    [Extra33]      NVARCHAR (30)  NULL,
    [Extra34]      NVARCHAR (30)  NULL,
    [Extra35]      NVARCHAR (30)  NULL,
    [Extra36]      NVARCHAR (30)  NULL,
    [Extra37]      NVARCHAR (30)  NULL,
    [Extra38]      NVARCHAR (30)  NULL,
    [Extra39]      NVARCHAR (30)  NULL,
    [Extra40]      NVARCHAR (30)  NULL,
    [Extra41]      NVARCHAR (30)  NULL,
    [Extra42]      NVARCHAR (30)  NULL,
    [Extra43]      NVARCHAR (30)  NULL,
    [Extra44]      NVARCHAR (30)  NULL,
    [Extra45]      NVARCHAR (30)  NULL,
    [Extra46]      NVARCHAR (30)  NULL,
    [Extra47]      NVARCHAR (30)  NULL,
    [Extra48]      NVARCHAR (30)  NULL,
    [Extra49]      NVARCHAR (30)  NULL,
    [ExOption00]   NVARCHAR (100) NULL,
    [ExOption01]   NVARCHAR (100) NULL,
    [ExOption02]   NVARCHAR (100) NULL,
    [ExOption03]   NVARCHAR (100) NULL,
    [ExOption04]   NVARCHAR (100) NULL,
    [ExOption05]   NVARCHAR (100) NULL,
    [ExOption06]   NVARCHAR (100) NULL,
    [ExOption07]   NVARCHAR (100) NULL,
    [ExOption08]   NVARCHAR (100) NULL,
    [ExOption09]   NVARCHAR (100) NULL,
    [ExOption10]   NVARCHAR (100) NULL,
    [ExOption11]   NVARCHAR (100) NULL,
    [ExOption12]   NVARCHAR (100) NULL,
    [ExOption13]   NVARCHAR (100) NULL,
    [ExOption14]   NVARCHAR (100) NULL,
    [ExOption15]   NVARCHAR (100) NULL,
    [ExOption16]   NVARCHAR (100) NULL,
    [ExOption17]   NVARCHAR (100) NULL,
    [ExOption18]   NVARCHAR (100) NULL,
    [ExOption19]   NVARCHAR (100) NULL,
    [ExOption20]   NVARCHAR (100) NULL,
    [ExOption21]   NVARCHAR (100) NULL,
    [ExOption22]   NVARCHAR (100) NULL,
    [ExOption23]   NVARCHAR (100) NULL,
    [ExOption24]   NVARCHAR (100) NULL,
    [ExOption25]   NVARCHAR (100) NULL,
    [ExOption26]   NVARCHAR (100) NULL,
    [ExOption27]   NVARCHAR (100) NULL,
    [ExOption28]   NVARCHAR (100) NULL,
    [ExOption29]   NVARCHAR (100) NULL,
    [ExOption30]   NVARCHAR (100) NULL,
    [ExOption31]   NVARCHAR (100) NULL,
    [ExOption32]   NVARCHAR (100) NULL,
    [ExOption33]   NVARCHAR (100) NULL,
    [ExOption34]   NVARCHAR (100) NULL,
    [ExOption35]   NVARCHAR (100) NULL,
    [ExOption36]   NVARCHAR (100) NULL,
    [ExOption37]   NVARCHAR (100) NULL,
    [ExOption38]   NVARCHAR (100) NULL,
    [ExOption39]   NVARCHAR (100) NULL,
    [ExOption40]   NVARCHAR (100) NULL,
    [ExOption41]   NVARCHAR (100) NULL,
    [ExOption42]   NVARCHAR (100) NULL,
    [ExOption43]   NVARCHAR (100) NULL,
    [ExOption44]   NVARCHAR (100) NULL,
    [ExOption45]   NVARCHAR (100) NULL,
    [ExOption46]   NVARCHAR (100) NULL,
    [ExOption47]   NVARCHAR (100) NULL,
    [ExOption48]   NVARCHAR (100) NULL,
    [ExOption49]   NVARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([DpmSeq] ASC) ON [PRIMARY]
) ON [PRIMARY];";

        public string DynamicPageDetail =
@"CREATE TABLE [dbo].[DynamicPageDetail] (
    [DpdSeq]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [DpmSeq]       INT            NOT NULL,
    [RegistDate]   DATETIME2 (7)  NOT NULL,
    [RegistMember] BIGINT         NOT NULL,
    [LastUpdate]   DATETIME2 (7)  NOT NULL,
    [UpdateMember] BIGINT         NOT NULL,
    [IsEnabled]    BIT            NOT NULL,
    [Extra00]      NVARCHAR (255) NULL,
    [Extra01]      NVARCHAR (255) NULL,
    [Extra02]      NVARCHAR (255) NULL,
    [Extra03]      NVARCHAR (255) NULL,
    [Extra04]      NVARCHAR (255) NULL,
    [Extra05]      NVARCHAR (255) NULL,
    [Extra06]      NVARCHAR (255) NULL,
    [Extra07]      NVARCHAR (255) NULL,
    [Extra08]      NVARCHAR (255) NULL,
    [Extra09]      NVARCHAR (255) NULL,
    [Extra10]      NVARCHAR (255) NULL,
    [Extra11]      NVARCHAR (255) NULL,
    [Extra12]      NVARCHAR (255) NULL,
    [Extra13]      NVARCHAR (255) NULL,
    [Extra14]      NVARCHAR (255) NULL,
    [Extra15]      NVARCHAR (255) NULL,
    [Extra16]      NVARCHAR (255) NULL,
    [Extra17]      NVARCHAR (255) NULL,
    [Extra18]      NVARCHAR (255) NULL,
    [Extra19]      NVARCHAR (255) NULL,
    [Extra20]      NVARCHAR (255) NULL,
    [Extra21]      NVARCHAR (255) NULL,
    [Extra22]      NVARCHAR (255) NULL,
    [Extra23]      NVARCHAR (255) NULL,
    [Extra24]      NVARCHAR (255) NULL,
    [Extra25]      NVARCHAR (255) NULL,
    [Extra26]      NVARCHAR (255) NULL,
    [Extra27]      NVARCHAR (255) NULL,
    [Extra28]      NVARCHAR (255) NULL,
    [Extra29]      NVARCHAR (255) NULL,
    [Extra30]      NVARCHAR (255) NULL,
    [Extra31]      NVARCHAR (255) NULL,
    [Extra32]      NVARCHAR (255) NULL,
    [Extra33]      NVARCHAR (255) NULL,
    [Extra34]      NVARCHAR (255) NULL,
    [Extra35]      NVARCHAR (255) NULL,
    [Extra36]      NVARCHAR (255) NULL,
    [Extra37]      NVARCHAR (255) NULL,
    [Extra38]      NVARCHAR (255) NULL,
    [Extra39]      NVARCHAR (255) NULL,
    [Extra40]      NVARCHAR (255) NULL,
    [Extra41]      NVARCHAR (255) NULL,
    [Extra42]      NVARCHAR (255) NULL,
    [Extra43]      NVARCHAR (255) NULL,
    [Extra44]      NVARCHAR (255) NULL,
    [Extra45]      NVARCHAR (255) NULL,
    [Extra46]      NVARCHAR (255) NULL,
    [Extra47]      NVARCHAR (255) NULL,
    [Extra48]      NVARCHAR (255) NULL,
    [Extra49]      NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([DpdSeq] ASC) ON [PRIMARY]
) ON [PRIMARY];";
    }
}
